### ISSUE TITLE
StringIndexOutOfBoundsException at MapRoutingTypes.encodeEntity

### ISSUE THREAD

**Issue by Diomas** [osmandapp/OsmAnd-tools#101]
I get an error when ways are processed in this file: https://yadi.sk/d/s8YrBaHXh63HH (I've cut a stripe along my route from Sweden and Denmark bpf files and merge them into single pbf)

Here is the log:
```
...
FINE: Memory before task exec: 566755328 free : 348851016
Jun 04, 2015 10:46:37 PM net.osmand.swing.ProgressDialog startTask
FINE: Processing osm nodes… started after 787 ms
Jun 04, 2015 10:48:07 PM net.osmand.swing.ProgressDialog startTask
FINE: Memory before task exec: 580911104 free : 224063344
Jun 04, 2015 10:48:07 PM net.osmand.swing.ProgressDialog startTask
FINE: Processing osm ways… started after 90061 ms
Jun 04, 2015 10:48:51 PM net.osmand.data.preparation.IndexCreator generateIndexes
SEVERE: Log exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at net.osmand.osm.MapRoutingTypes.encodeEntity(MapRoutingTypes.java:206)
	at net.osmand.data.preparation.IndexRouteCreator.iterateMainEntity(IndexRouteCreator.java:169)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:239)
	at net.osmand.data.preparation.IndexCreator.access$1000(IndexCreator.java:48)
	at net.osmand.data.preparation.IndexCreator$10.iterateEntity(IndexCreator.java:613)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:241)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:195)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:610)
	at net.osmand.swing.OsmExtractionUI$13.run(OsmExtractionUI.java:547)
	at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)

Jun 04, 2015 10:48:52 PM net.osmand.swing.ExceptionHandler handle
SEVERE: Exception during operation
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at net.osmand.osm.MapRoutingTypes.encodeEntity(MapRoutingTypes.java:206)
	at net.osmand.data.preparation.IndexRouteCreator.iterateMainEntity(IndexRouteCreator.java:169)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:239)
	at net.osmand.data.preparation.IndexCreator.access$1000(IndexCreator.java:48)
	at net.osmand.data.preparation.IndexCreator$10.iterateEntity(IndexCreator.java:613)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:241)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:195)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:610)
	at net.osmand.swing.OsmExtractionUI$13.run(OsmExtractionUI.java:547)
	at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)
```

**Comment by aceman444** [comment]
Hi. Thanks that you fixed the error. But now how do we implement the removed line "<routing_type tag="pedestrian" tag2="foot" mode="replace"/>" correctly? It should just convert one tag key to another but copy (not touch) the value. What is the proper syntax of that?
