### ISSUE TITLE
Null Pointer Exception during IndexCreator.generateIndexes

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/OsmAnd-tools#102]
I used the Geofabrik england-latest.osm.pbf (594 MB) from 10th July 2015 with OsmMap Creator on Win 7 x64 (6 GB RAM, -Xmx4096M) for HDD-based full index OBF creation and after 48 hours it disappointingly failed with a null-pointer exception leaving a 10 GB nodes.tmp.odb file:

	Jul 13, 2015 3:35:49 AM net.osmand.data.preparation.IndexCreator generateIndexes
	SEVERE: Log exception
	java.lang.NullPointerException
	at net.osmand.osm.edit.OsmMapUtils.ray_intersect_lon(OsmMapUtils.java:348)
	at net.osmand.util.MapAlgorithms.countIntersections(MapAlgorithms.java:326)
	at net.osmand.util.MapAlgorithms.containsPoint(MapAlgorithms.java:295)
	at net.osmand.osm.edit.OsmMapUtils.getWeightCenterForWay(OsmMapUtils.java:94)
	at net.osmand.osm.edit.OsmMapUtils.getCenter(OsmMapUtils.java:31)
	at net.osmand.osm.edit.EntityParser.parseMapObject(EntityParser.java:50)
	at net.osmand.osm.edit.EntityParser.parseAmenities(EntityParser.java:187)
	at net.osmand.data.preparation.IndexPoiCreator.iterateEntity(IndexPoiCreator.java:98)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:230)
	at net.osmand.data.preparation.IndexCreator.access$100(IndexCreator.java:51)
	at net.osmand.data.preparation.IndexCreator$6.iterateEntity(IndexCreator.java:725)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:244)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:198)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntities(IndexCreator.java:722)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:567)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:479)
	at net.osmand.swing.OsmExtractionUI$13.run(OsmExtractionUI.java:547)
	at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)

Full log file (160 kB zip) available at http://1drv.ms/1O5AjWt

**Comment by vshcherb** [comment]
Fixed
