### ISSUE TITLE
UnsupportedOperationException while trying to generate some maps

### ISSUE THREAD

**Issue by naoliv** [osmandapp/OsmAnd-tools#104]
I am seeing this while trying to generate some maps with the latest mapcreator:

```
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1342)
	at net.osmand.osm.MapRenderingTypesEncoder.prepareColorTag(MapRenderingTypesEncoder.java:459)
	at net.osmand.osm.MapRenderingTypesEncoder.processExtraTags(MapRenderingTypesEncoder.java:640)
	at net.osmand.osm.MapRenderingTypesEncoder.getRelationPropogatedTags(MapRenderingTypesEncoder.java:73)
	at net.osmand.data.preparation.IndexVectorMapCreator.indexMapRelationsAndMultiPolygons(IndexVectorMapCreator.java:115)
	at net.osmand.data.preparation.IndexCreator$9.iterateEntity(IndexCreator.java:783)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:252)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:206)
	at net.osmand.data.preparation.IndexCreator.indexRelations(IndexCreator.java:775)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:594)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:518)
	at net.osmand.data.index.IndexBatchCreator.generateIndex(IndexBatchCreator.java:552)
	at net.osmand.data.index.IndexBatchCreator.generatedIndexes(IndexBatchCreator.java:464)
	at net.osmand.data.index.IndexBatchCreator.runBatch(IndexBatchCreator.java:310)
	at net.osmand.data.index.IndexBatchCreator.main(IndexBatchCreator.java:163)
```

**Comment by xmd5a2** [comment]
Duplicate https://github.com/osmandapp/Osmand/issues/1628
