### ISSUE TITLE
error while converting: java.lang.unsupportedoperationexception

### ISSUE THREAD

**Issue by Nichtraucher** [osmandapp/OsmAnd-tools#105]
In osmand map creator:

I was about to make several different (unselecting different indexes in the gui) conversions of one particular .pbf to see how they differ in file size etc. The conversion with only routing and address-index selected failed. A window popped up with above mentioned eror message. Here's an excerpt of the terminal output:

> Okt 30, 2015 2:56:06 PM net.osmand.data.preparation.IndexCreator generateIndexes
SCHWERWIEGEND: Log exception
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1342)
	at net.osmand.data.preparation.IndexRouteCreator.iterateMainEntity(IndexRouteCreator.java:175)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:252)
	at net.osmand.data.preparation.IndexCreator.access$200(IndexCreator.java:50)
	at net.osmand.data.preparation.IndexCreator$7.iterateEntity(IndexCreator.java:758)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:252)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:206)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntities(IndexCreator.java:755)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:596)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:518)
	at net.osmand.swing.OsmExtractionUI$13.run(OsmExtractionUI.java:547)
	at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)

> Okt 30, 2015 2:56:07 PM net.osmand.swing.ExceptionHandler handle
SCHWERWIEGEND: Exception during operation
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1342)
	at net.osmand.data.preparation.IndexRouteCreator.iterateMainEntity(IndexRouteCreator.java:175)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:252)
	at net.osmand.data.preparation.IndexCreator.access$200(IndexCreator.java:50)
	at net.osmand.data.preparation.IndexCreator$7.iterateEntity(IndexCreator.java:758)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:252)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:206)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntities(IndexCreator.java:755)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:596)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:518)
	at net.osmand.swing.OsmExtractionUI$13.run(OsmExtractionUI.java:547)
	at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)

> java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableMap.put(Collections.java:1342)
	at net.osmand.data.preparation.IndexRouteCreator.iterateMainEntity(IndexRouteCreator.java:175)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:252)
	at net.osmand.data.preparation.IndexCreator.access$200(IndexCreator.java:50)
	at net.osmand.data.preparation.IndexCreator$7.iterateEntity(IndexCreator.java:758)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:252)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:206)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntities(IndexCreator.java:755)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:596)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:518)
	at net.osmand.swing.OsmExtractionUI$13.run(OsmExtractionUI.java:547)
	at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)

Is there anything I could do to prevent this from happening again?

/addendum: I had the same problem with other maps but only with this particular index configuration.

**Comment by vshcherb** [comment]
The map creator looks like to be updated, the lines don't match.
