### ISSUE TITLE
OsmAndMapCreator.bat does not work on Windows 7 64bit

### ISSUE THREAD

**Issue by jalil1408** [osmandapp/OsmAnd-tools#129]
using ConEmu:

user@PC C:\Users\user\Desktop\OsmAndMapCreator-main
$ OsmAndMapCreator.bat

user@PC C:\Users\user\Desktop\OsmAndMapCreator-main
$ REM the JVM. With the below settings the heap size (Available memory for the application)

user@PC C:\Users\user\Desktop\OsmAndMapCreator-main
$ REM will range from 64 megabyte up to 720 megabyte.

user@PC C:\Users\user\Desktop\OsmAndMapCreator-main
$ start javaw.exe -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx720M -cp "./OsmAndMapCreator.jar;./lib/OsmAnd-core.jar;./lib/*.jar;./lib-gl/*.jar" net.osmand.swing.OsmExtractionUI

user@PC C:\Users\user\Desktop\OsmAndMapCreator-main
$

**Comment by vshcherb** [comment]
I'm not currently able to test it. Is it an issue related to  ConEmu? Any crashes?

**Comment by jalil1408** [comment]
No, I tested it with the Command Prompt (cmd.exe) and it didn't start. There is no output or log!

**Comment by vshcherb** [comment]
The bat file is very simple https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/OsmAndMapCreator.bat.

So please open command line and run directly this line:
java.exe -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx720M -cp "./OsmAndMapCreator.jar;./lib/OsmAnd-core.jar;./lib/*.jar;./lib-gl/*.jar" net.osmand.swing.OsmExtractionUI

**Comment by vshcherb** [comment]
It should run in folder with OsmAndMapCreator.jar

**Comment by jalil1408** [comment]
I got this now:

user@PC d:\soft\OsmAndMapCreator-main
$ java.exe -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx720M -cp "./OsmAndMapCreator.jar;./lib/OsmAnd-core.jar;./lib/.jar;./lib-gl/.jar" net.osmand.swing.OsmExtractionUI
Jul 31, 2016 11:50:30 AM net.osmand.osm.MapPoiTypes init
INFO: Time to init poi types 27
Jul 31, 2016 11:50:30 AM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Search is done. Visit 2235 objects. Read 2235 objects.
Jul 31, 2016 11:50:30 AM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Read 59 subtrees. Go through 115 subtrees.
Jul 31, 2016 11:50:30 AM net.osmand.swing.ExceptionHandler handle
SEVERE: Error in thread main
com.google.protobuf.UninitializedMessageException: Message was missing required fields.  (Lite runtime could not determine which fields were missing).
        at com.google.protobuf.AbstractMessageLite$Builder.newUninitializedMessageException(AbstractMessageLite.java:306)
        at net.osmand.binary.OsmandIndex$OsmAndStoredIndex$Builder.build(OsmandIndex.java:215)
        at net.osmand.binary.CachedOsmandIndexes.readFromFile(CachedOsmandIndexes.java:311)
        at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:212)
        at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:166)
        at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:128)

com.google.protobuf.UninitializedMessageException: Message was missing required fields.  (Lite runtime could not determine which fields were missing).
        at com.google.protobuf.AbstractMessageLite$Builder.newUninitializedMessageException(AbstractMessageLite.java:306)
        at net.osmand.binary.OsmandIndex$OsmAndStoredIndex$Builder.build(OsmandIndex.java:215)
        at net.osmand.binary.CachedOsmandIndexes.readFromFile(CachedOsmandIndexes.java:311)
        at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:212)
        at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:166)
        at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:128)

user@PC d:\soft\OsmAndMapCreator-main
$

**Comment by vshcherb** [comment]
just delete indexes.cache from folder

**Comment by jalil1408** [comment]
Now it works after deleting indexes.cache.
Thank you @vshcherb
