### ISSUE TITLE
com.google.protobuf.UninitializedMessageException: Message was missing required fields

### ISSUE THREAD

**Issue by int-ua** [osmandapp/OsmAnd-tools#130]
OsmAndMapCreator: today's nightly build, 2016-09-30
Ubuntu 16.04, same results with Oracle jdk1.8.0_101 and OpenJDK 8u91-b14-3ubuntu1~16.04.1
```
$ bash OsmAndMapCreator.sh
вер. 30, 2016 1:41:50 PM net.osmand.osm.MapPoiTypes init
INFO: Time to init poi types 42
вер. 30, 2016 1:41:50 PM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Search is done. Visit 2234 objects. Read 2234 objects.
вер. 30, 2016 1:41:50 PM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Read 59 subtrees. Go through 115 subtrees.
вер. 30, 2016 1:41:50 PM net.osmand.swing.ExceptionHandler handle
SEVERE: Error in thread main
com.google.protobuf.UninitializedMessageException: Message was missing required fields.  (Lite runtime could not determine which fields were missing).
        at com.google.protobuf.AbstractMessageLite$Builder.newUninitializedMessageException(AbstractMessageLite.java:306)
        at net.osmand.binary.OsmandIndex$OsmAndStoredIndex$Builder.build(OsmandIndex.java:215)
        at net.osmand.binary.CachedOsmandIndexes.readFromFile(CachedOsmandIndexes.java:311)
        at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:213)
        at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:167)
        at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:129)

com.google.protobuf.UninitializedMessageException: Message was missing required fields.  (Lite runtime could not determine which fields were missing).
        at com.google.protobuf.AbstractMessageLite$Builder.newUninitializedMessageException(AbstractMessageLite.java:306)
        at net.osmand.binary.OsmandIndex$OsmAndStoredIndex$Builder.build(OsmandIndex.java:215)
        at net.osmand.binary.CachedOsmandIndexes.readFromFile(CachedOsmandIndexes.java:311)
        at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:213)
        at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:167)
        at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:129)
```
And http://download.osmand.net/latest-night-build/OsmAndMapCreator-main-24-04.zip crashes java.

**Comment by hakuchi** [comment]
same error if I start OsmAndMapCreator

**Comment by vshcherb** [comment]
Can you delete osmand_indexes file in the map folder

**Comment by hakuchi** [comment]
there is no indexes file anywhere on my pc

**Comment by vshcherb** [comment]
There must be indexes.cache file in directory with obf maps.

**Comment by int-ua** [comment]
I don't have any obfs yet, I wanted to convert a pbf myself. Anyway, I don't remember seeing anything in docs about where to put maps, was trying to launch it before downloading maps.

**Comment by vshcherb** [comment]
Yes, but the stacktrace you shared points to this line https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/src/net/osmand/swing/OsmExtractionUI.java#L213
Which is executed only when indexes.cache exist.

**Comment by int-ua** [comment]
Ok, I'll try to delete it later, thank you.

**Comment by hakuchi** [comment]
now for me it works. thx vscherb

I copied a .obf from the OsmAnd folder from my phone to ...\OsmAndMapCreator-main
then I deleted indexes.cache inside ...\OsmAndMapCreator-main
after this two simple steps the mapcreator works fine and generating a map from a .osm or .pbf works perfect

**Comment by rogerjames99** [comment]
Hi I have got past the L213 crash by deleting the indexes.cache file. But now it crashes with the following.

`Oct 07, 2016 6:14:58 PM net.osmand.osm.MapPoiTypes init
INFO: Time to init poi types 58
Oct 07, 2016 6:14:59 PM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Search is done. Visit 2234 objects. Read 2234 objects.
Oct 07, 2016 6:14:59 PM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Read 59 subtrees. Go through 115 subtrees.
Oct 07, 2016 6:14:59 PM net.osmand.swing.ExceptionHandler handle
SEVERE: Error in thread main
java.lang.NullPointerException
	at net.osmand.binary.CachedOsmandIndexes.writeToFile(CachedOsmandIndexes.java:326)
	at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:232)
	at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:167)
	at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:129)

java.lang.NullPointerException
	at net.osmand.binary.CachedOsmandIndexes.writeToFile(CachedOsmandIndexes.java:326)
	at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:232)
	at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:167)
	at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:129)
`

**Comment by Pastim** [comment]
I get the same as rogerjames99 .  I then built a new OsmAndMapCreator (from https://code.google.com/archive/p/osmand/wikis/CommandLineBuildEnvironment.wiki) and got the same problem.  The old (April) version works.  

I also tried with no 'mapbuild' directory set up.  One was created before the error occurred.

**Comment by Pastim** [comment]
Has this been fixed?  I still get the error and no files seem to have been changed, or have I missed something?

**Comment by vshcherb** [comment]
Just fixed, though the file need to be deleted still before run.

**Comment by Pastim** [comment]
Thanks very much.  I'll download the nightly zip tomorrow and try it.

**Comment by Pastim** [comment]
Just tested it - it's fine.  Thanks very much.
