### ISSUE TITLE
Problem processing 64-bit way ids

### ISSUE THREAD

**Issue by TimSC** [osmandapp/OsmAnd-tools#134]
Using OsmAndMapCreator 18339, I get the error below. I can provide the pbf input file if that is helpful.

```
Feb 04, 2017 11:27:50 PM net.osmand.swing.ExceptionHandler handle
SEVERE: Exception during operation
java.lang.IllegalStateException: Way id too big
	at net.osmand.data.preparation.IndexRouteCreator.registerBaseIntersectionPoint(IndexRouteCreator.java:245)
	at net.osmand.data.preparation.IndexRouteCreator.simplifyRouteForBaseSection(IndexRouteCreator.java:222)
	at net.osmand.data.preparation.IndexRouteCreator.iterateMainEntity(IndexRouteCreator.java:200)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:286)
	at net.osmand.data.preparation.IndexCreator.access$200(IndexCreator.java:55)
	at net.osmand.data.preparation.IndexCreator$6.iterateEntity(IndexCreator.java:815)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:253)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:207)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntities(IndexCreator.java:812)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:670)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:590)
	at net.osmand.swing.OsmExtractionUI$18.run(OsmExtractionUI.java:799)
	at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)

java.lang.IllegalStateException: Way id too big
	at net.osmand.data.preparation.IndexRouteCreator.registerBaseIntersectionPoint(IndexRouteCreator.java:245)
	at net.osmand.data.preparation.IndexRouteCreator.simplifyRouteForBaseSection(IndexRouteCreator.java:222)
	at net.osmand.data.preparation.IndexRouteCreator.iterateMainEntity(IndexRouteCreator.java:200)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntity(IndexCreator.java:286)
	at net.osmand.data.preparation.IndexCreator.access$200(IndexCreator.java:55)
	at net.osmand.data.preparation.IndexCreator$6.iterateEntity(IndexCreator.java:815)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:253)
	at net.osmand.data.preparation.OsmDbAccessor.iterateOverEntities(OsmDbAccessor.java:207)
	at net.osmand.data.preparation.IndexCreator.iterateMainEntities(IndexCreator.java:812)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:670)
	at net.osmand.data.preparation.IndexCreator.generateIndexes(IndexCreator.java:590)
	at net.osmand.swing.OsmExtractionUI$18.run(OsmExtractionUI.java:799)
	at net.osmand.swing.ProgressDialog$WorkerThread.run(ProgressDialog.java:87)


```

**Comment by vshcherb** [comment]
Unfortunately it is a legacy design problem. The maximum way number is 68 719 476 736 today.

**Comment by TimSC** [comment]
I am working with a different dataset with much higher IDs. Unless it is fairly trivial fix (and I guess it isn't), I'm going to have to renumber my ways(?).

**Comment by vshcherb** [comment]
It definitely not possible to fix today, cause the way/point id is limited by 64 bits in the code
long genKey = register ? ((wayId << (SHIFT_ORIGINAL+SHIFT_INSERT_AT)) + (originalInd << SHIFT_INSERT_AT) + insertAt) : -1l;

I believe it is possible to recompile MapCreator and changes constans and give it a try
private static long SHIFT_INSERT_AT = 12;
private static long SHIFT_ORIGINAL = 16;
private static long SHIFT_ID = 64 - (SHIFT_INSERT_AT + SHIFT_ORIGINAL);

I do believe renumbering ways would be easier.

**Comment by TimSC** [comment]
Thanks, I'll try renumbering for now!
