### ISSUE TITLE
OsmAndTools : NullPointerException while indexing boundaries from relation on a ᴍᴀᴘ of mine

### ISSUE THREAD

**Issue by ytrezq** [osmandapp/OsmAnd-tools#325]
at javax.swing.plaf.basic.BasicProgressBarUI.updateSizes(Unknown Source)
        at javax.swing.plaf.basic.BasicProgressBarUI.getBox(Unknown Source)
        at javax.swing.plaf.basic.BasicProgressBarUI.paintIndeterminate(Unknown Source)
        at javax.swing.plaf.metal.MetalProgressBarUI.paintIndeterminate(Unknown Source)
        at javax.swing.plaf.basic.BasicProgressBarUI.paint(Unknown Source)
        at javax.swing.plaf.ComponentUI.update(Unknown Source)
        at javax.swing.JComponent.paintComponent(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent._paintImmediately(Unknown Source)
        at javax.swing.JComponent.paintImmediately(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at java.awt.Component.show(Unknown Source)
        at java.awt.Component.setVisible(Unknown Source)
        at java.awt.Window.setVisible(Unknown Source)
        at java.awt.Dialog.setVisible(Unknown Source)
        at net.osmand.swing.ProgressDialog.run(ProgressDialog.java:62)
        at net.osmand.swing.OsmExtractionUI.loadCountry(OsmExtractionUI.java:855)
        at net.osmand.swing.OsmExtractionUI$16.actionPerformed(OsmExtractionUI.java:747)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

The map which trigger this can be downloaded [here](http://ytrezq.sdfeu.org/France_centre-loire-valley_europe.road.pbf). Of course, it happens with the official ᴊᴠᴍ binaries from Oracle.

It requires 135Gb of ʀᴀᴍ for correct processing, but the Linux server being used has way more than that and the ᴊᴠᴍ memory parameter are set accordingly.

**Comment by vshcherb** [comment]
It doesn't require 135GB at least we don't have so much to produce these maps. It is better to use command line tool utlitlies.sh to generate map instea of UI.

**Comment by ytrezq** [comment]
Are you talking about the command line version of ᴏꜱᴍAndMapCreator ? If yes, it does require even more ʀᴀᴍ that.

**Comment by vshcherb** [comment]
This is command line
https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndServerUtilities/utilities.sh
You probably use sqlite_in_memory
https://github.com/osmandapp/OsmAnd-tools/blob/master/obf-generation/indexes-batch-generate-inmem.xml

Which could be changed to sqlite and loose some speed but it might be not critical

**Comment by ytrezq** [comment]
@vshcherb with `sqlite_in_memory` ʀᴀᴍ usage is 340Gb.

**Comment by vshcherb** [comment]
Yes, you should try sqlite if you are interested in lower memory consumption

**Comment by ytrezq** [comment]
@vshcherb this is not the point of the bug. The point is this [map](http://ytrezq.sdfeu.org/France_centre-loire-valley_europe.road.pbf) triggers a backtrace unrelated to memory consumption which prevent outputing a map without errors.
**Please reopen!**

**Comment by vshcherb** [comment]
I got the point, though it is not going to be fixed cause there are workarounds and it is not reproducible during main OSM map creation.
