### ISSUE TITLE
OsmAndMapCreator crashes when started from a path where a folder ends in !

### ISSUE THREAD

**Issue by ganego** [osmandapp/OsmAnd-tools#363]
If any folder in the path MapCreator is in, ends in an `!` the program will crash on start.  
To be able to see the error, start via `java -jar OsmAndMapCreator.jar`

Example paths:
`C:\a!\OsmAndMapCreator-main`  
`C:\OsmAndMapCreator-main!`

Error:
```
net.osmand.swing.ExceptionHandler handle
SEVERE: Error in thread main
java.lang.ExceptionInInitializerError
        at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:172)
        at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:168)
        at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:130)
Caused by: java.util.MissingResourceException: Can't find bundle for base name net.osmand.swing.swing_messages, locale en_US
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
        at net.osmand.swing.Messages.<clinit>(Messages.java:9)
        ... 3 more
Caused by: java.nio.file.NoSuchFileException: C:\a
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:825)
        at java.base/java.util.zip.ZipFile$CleanableResource$FinalizableResource.<init>(ZipFile.java:851)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:840)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
        at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
        at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3227)
        at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3216)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3215)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
        ... 7 more

java.lang.ExceptionInInitializerError
        at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:172)
        at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:168)
        at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:130)
Caused by: java.util.MissingResourceException: Can't find bundle for base name net.osmand.swing.swing_messages, locale en_US
        at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:857)
        at net.osmand.swing.Messages.<clinit>(Messages.java:9)
        ... 3 more
Caused by: java.nio.file.NoSuchFileException: C:\a
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:198)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:825)
        at java.base/java.util.zip.ZipFile$CleanableResource$FinalizableResource.<init>(ZipFile.java:851)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:840)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:103)
        at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:72)
        at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
        at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3227)
        at java.base/java.util.ResourceBundle$Control$1.run(ResourceBundle.java:3216)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3215)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
        ... 7 more
```

**Comment by vshcherb** [comment]
This looks like a script problem or problem with JDK

**Comment by ganego** [comment]
Interesting, it's indeed some long-lasting JVM bug: 
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4523159  

Oh well, then I'll close the issue.
