### ISSUE TITLE
Filenames not escaped in OsmAndMapCreatorUtilities

### ISSUE THREAD

**Issue by frafra** [osmandapp/OsmAnd-tools#619]
Cannot process files containing `'` characters, as the argument is not escaped:

https://github.com/osmandapp/OsmAnd-tools/blob/9a74f636f74dca41eb919a21b8b93ae94f8bcb57/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexCreator.java#L391-L392

Here is the log:

```
[...]
INFO: Task loading_file/extrastoragebig/estratti/output/dati/poly/regioni/pbf/02_Valle d'Aosta - Vallée d'Aoste.osm.pbf is finished 
May 10, 2023 1:31:57 AM net.osmand.obf.preparation.IndexCreator extractOsmToNodesDB
INFO: File parsed : 40291
May 10, 2023 1:31:57 AM net.osmand.impl.ConsoleProgressImplementation finishTask
INFO: Task null is finished 
May 10, 2023 1:31:57 AM net.osmand.obf.preparation.IndexCreator extractOsmToNodesDB
INFO: File indexed : 40291
May 10, 2023 1:31:57 AM net.osmand.obf.preparation.IndexCreator generateIndexes
SEVERE: Log exception
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (near "Aosta": syntax error)
        at org.sqlite.DB.newSQLException(DB.java:383)
        at org.sqlite.DB.newSQLException(DB.java:387)
        at org.sqlite.DB.throwex(DB.java:374)
        at org.sqlite.NativeDB.prepare(Native Method)
        at org.sqlite.DB.prepare(DB.java:123)
        at org.sqlite.Stmt.execute(Stmt.java:113)
        at net.osmand.obf.preparation.IndexCreator.initDbAccessor(IndexCreator.java:391)
        at net.osmand.obf.preparation.IndexCreator.generateIndexes(IndexCreator.java:618)
        at net.osmand.obf.preparation.IndexCreator.generateIndexes(IndexCreator.java:538)
        at net.osmand.util.IndexBatchCreator.generateLocalIndex(IndexBatchCreator.java:811)
        at net.osmand.util.IndexBatchCreator.runBatch(IndexBatchCreator.java:387)
        at net.osmand.util.IndexBatchCreator.main(IndexBatchCreator.java:178)
```

I would suggest using the same measures used to fix SQL injection vulnerabilities, such as prepared statements.

**Comment by frafra** [comment]
Fixed by 11be85bb63b590e77b83ecc711386b8aad29ce31. Not a great way to deal with the community, but the bug has been fixed at least :)
