### ISSUE TITLE
can't create single gpx file as obf

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd-tools#766]
command `./utilities.sh convert-gpx-to-obf 2023-OM-FULL.gpx `

error msg :

```
java.lang.NullPointerException: Cannot invoke "java.io.File.getPath()" because the return value of "java.io.File.getParentFile()" is null
        at net.osmand.obf.OsmGpxWriteContext.generateObfFromGpx(OsmGpxWriteContext.java:419)
        at net.osmand.MainUtilities.mainException(MainUtilities.java:183)
        at net.osmand.MainUtilities.main(MainUtilities.java:76)
```

I have to move the file to subdirectory then utilities works OK

**Comment by vshcherb** [comment]
That's strange
