### ISSUE TITLE
MapCreator crashed changing to vector layer and won't start again

### ISSUE THREAD

**Issue by Hedaja** [osmandapp/OsmAnd-tools#967]
Hi
When I tried using a vector layer background, the Creator crashed. No trying to start it, I get the following error messages in the terminal.
```
net.osmand.swing.ExceptionHandler handle
SCHWERWIEGEND: Error in thread main
java.lang.NullPointerException: Cannot read the array length because "<local5>" is null
	at net.osmand.swing.DataExtractionSettings.getObfReaders(DataExtractionSettings.java:62)
	at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:206)
	at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:166)
	at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:128)

java.lang.NullPointerException: Cannot read the array length because "<local5>" is null
	at net.osmand.swing.DataExtractionSettings.getObfReaders(DataExtractionSettings.java:62)
	at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:206)
	at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:166)
	at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:128)
```

I also tried completely removing the software and downloading it again. 
Is it possible that settings get stored outside of the application folder and that it's trying to load the vector background again and crashing because of that?

```
System Info:
# System Details Report
---

## Report details
- **Date generated:**                              2024-11-13 09:27:15

## Hardware Information:
- **Hardware Model:**                              HP HP Elite x2 1012 G2
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-7200U × 4
- **Graphics:**                                    Intel® HD Graphics 620 (KBL GT2)
- **Disk Capacity:**                               256.1 GB

## Software Information:
- **Firmware Version:**                            P87 Ver. 01.48
- **OS Name:**                                     Ubuntu 24.10
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.0-9-generic

```

**Comment by vadimceb** [comment]
Faced same issue recently while trying to create a custom style.

I had to edit the file at `~/.java/.userPrefs/prefs.xml`
and remove the key `binaryFilesDir`.
_This is intended as a workaround_

**Comment by Hedaja** [comment]
Thank you. That work-around worked for me as well.
